### ISSUE TITLE
Add possibility to select audio data source like external audio card

### ISSUE THREAD

**Issue by 452** [google/patchfield#3]
Add possibility to select audio data source from external audio card

I have external audio card, Nexus 7 can work with external audio card, but in SDK I have no see any for this.

mRecorder.setAudioSource(MediaRecorder.AudioSource.MIC);

but need something like this:
mRecorder.setAudioSource(MediaRecorder.AudioSource.EXTERNAL_CARD_MIC);

http://www.jakartanotebook.com/images/products/38/18/2387/1/vztec-usb-7.1-channel-sound-card-adapter-vz-ua3915-3.jpg

also need advanced audio API for using - Line IN from external audio card.

I wanted to create open source universal oscilloscope(with input data source plugins system) for android (also with a possibility to get data from 1.5 USD USB audio card), but I can't to do this easy.

this app can work with external audio card https://play.google.com/store/apps/details?id=de.sobe.usbaudio

but I think need SDK support.

**Comment by nettoyeurny** [comment]
Like you said, this is an SDK issue. We can't do anything about this here because Patchfield builds on top of the existing SDK. I'll close this issue now.
